# -*- coding: utf-8 -*-
"""Python course.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1txMaCyg2cH_bcldAhzqAlOkZ6qsaJ6
"""

t = (2, 3,4,5,"sudh",45.467, False, 45+47j, [3,4,5])
print(t)
print(type(t))
print(len(t))
print(t[0])
print((t[::-1]))

l4[0]=2345
l4

l4=["Rushi","Patil","Data science"]
print(l4)

l4[0]=234
print(l4)

t

t.count(5)

t.index(False)

s1={}
type(s1)

s2={2,3,4,5}
type(s2)

s3={3487,387,328,"Rush",45+8j,34.34,(2,3,4)}

s3
#list is not accepted because it accept only immutable

s4 ={2,4,3,3,3,4,2,4,2,5,6,7,8}

s4
#set keep only unique data...it remove all duplicates

s4={2,4,3,3,3,4,2,4,2,5,6,7,8,"rush","rush"}

s4
#Second rush is removed

l1=[2,4,3,3,3,4,2,4,2,5,6,7,8,"rush","rush"]
set(l1)
#it is set form

list(set(l1))
#now it is list form

s5={233,345,54,23232,5432,657,877,"abc"}

s5
#Set never arrange data in order

s5[0]

s5[::-1]
#Slicing and indexing operation is applied on set

s5.add(5)
#set create a hash so here we dont require to give index number.

s5

s5.remove(345)

s5

##############Class 3 dictionary#################

d = {}
type(d)

d1 = {'key' :"Rushi" }
d1

d2 = {'name' : "Rushi", "email": "rushi@gmail.com" , "number" : 12345}
d2

d3 = {True  : 123}
d3

d2

d2['name']

d3[1]

d4 = {'name':"rushi", 'mail id': "rushi@gmail.com", 'name': "rushikesh"}
d4

d4['name']

d5 = {'name': ["rushi", "ketkee"], 'id':123}
d5

d5['name']

d5["name"][1]

d6 = {'number': [2,34,3,34], "assignment": (1,2,3,4,5,6), "launch date": {28,12,14}, "class time":{"web_dev": 8, "data science master": 8, "java": 7}}
d6

d6["class time"]["java"]

d6

d6["mentor"]= ["rushi", "avi", "paddy"]
d6

del d6["mentor"]
d6

d6.keys()

d6.values()

list (d6.items())

##########control statement

marks = int(input("enter your marks"))
if marks >= 80 :
  print ("you will be part of A0 batch")
elif  marks >=60 and marks < 80:
  print("you will be part of A1 batch")
elif  marks >= 40 and marks < 60 :
  print("you will be part of A2 batch")
else :
  print ("You will be part of A3 batch")

price = int(input("enter price"))
if price > 1000:
  print("i will not purchase")
else:
  print("i will purchase")

price = int(input("enter price "))
if price > 1000:
  print("i will not purchase")
  if price >5000:
    print("its too much")
  elif price < 2000:
    print("its ok")

"""Loops :for loop"""

l = [1,2,3,4,5,6,7,8]
for i in l :
  print(i)

l = [1,2,3,4,5,6,7,8]
l1 = []
for i in l :
  print(i+1)
  l1.append(i+1)
l1

l  = ["rushi", "patil" , "myself", "work"]
 l1 = []
 for i in l :
  print(i)
  l1.append(i.upper())
l1

l = [1,2,3,4,4, "rushi", "patil", 342, 34.53, "abc"]

l = [1,2,3,4,4, "rushi", "patil", 342, 34.53, "abc"]
l1_num = []
l2_str = []
for i in l :
  if type(i) == int or type(i) == float :
    l1_num.append(i)
  else :
    l2_str.append(i)
l1_num

l1_num

l2_str